### ISSUE TITLE
not working when target framework changed to net6.0

### ISSUE THREAD

**Issue by bangush** [NorthwoodsSoftware/GoJS-Alongside-Blazor#2]
only show below text, when START THE DEBUG.

Loading....

**Comment by mhlee0328** [comment]
The project looks fine to me on the net6.0, just upgraded package by nuget.
vs2022 (17.1.4)
 - microsoft.aspnetcore.components.webassembly(6.0.4)
 - microsoft.aspnetcore.components.webassembly.devserver(6.0.4)
 - system.net.http.json(6.0.0)
